// Code generated by mockery 2.7.5. DO NOT EDIT.

package mocks

import (
	context "context"

	page "github.com/chromedp/cdproto/page"
	mock "github.com/stretchr/testify/mock"
)

// BrowserHandler is an autogenerated mock type for the BrowserHandler type
type BrowserHandler struct {
	mock.Mock
}

// Evaluate provides a mock function with given fields: ctx, script
func (_m *BrowserHandler) Evaluate(ctx context.Context, script string) ([]byte, error) {
	ret := _m.Called(ctx, script)

	var r0 []byte
	if rf, ok := ret.Get(0).(func(context.Context, string) []byte); ok {
		r0 = rf(ctx, script)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, script)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Navigate provides a mock function with given fields: ctx, urlstr
func (_m *BrowserHandler) Navigate(ctx context.Context, urlstr string) error {
	ret := _m.Called(ctx, urlstr)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, urlstr)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewContext provides a mock function with given fields: parent
func (_m *BrowserHandler) NewContext(parent context.Context) (context.Context, context.CancelFunc) {
	ret := _m.Called(parent)

	var r0 context.Context
	if rf, ok := ret.Get(0).(func(context.Context) context.Context); ok {
		r0 = rf(parent)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(context.Context)
		}
	}

	var r1 context.CancelFunc
	if rf, ok := ret.Get(1).(func(context.Context) context.CancelFunc); ok {
		r1 = rf(parent)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(context.CancelFunc)
		}
	}

	return r0, r1
}

// Screenshot provides a mock function with given fields: ctx, viewport
func (_m *BrowserHandler) Screenshot(ctx context.Context, viewport page.Viewport) ([]byte, error) {
	ret := _m.Called(ctx, viewport)

	var r0 []byte
	if rf, ok := ret.Get(0).(func(context.Context, page.Viewport) []byte); ok {
		r0 = rf(ctx, viewport)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, page.Viewport) error); ok {
		r1 = rf(ctx, viewport)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
