# Specify a command to be executed
# like '/bin/bash -l', 'ls', or any other commands
# the default is bash for Linux
# or powershell.exe for Windows
command: /bin/bash

# Specify the current working directory path
# the default is the current working directory path
cwd: /tmp

# Export additional ENV variables
env:
  PS1: '\[\e[34m\]\u\[\e[m\]\[\e[31m\]@\[\e[m\]\[\e[34m\]\h\[\e[m\]\[\e[32m\][\[\e[m\]\w\[\e[32m\]]\[\e[m\]\n>>> '

# Explicitly set the number of columns
# or use 'auto' to take the current
# number of columns of your shell
cols: auto

# Explicitly set the number of rows
# or use 'auto' to take the current
# number of rows of your shell
rows: auto

# Amount of times to repeat GIF
# If value is -1, play once
# If value is 0, loop indefinitely
# If value is a positive number, loop n times
repeat: 0

# Quality
# 1 - 100
quality: 100

# Delay between frames in ms
# If the value is 'auto' use the actual recording delays
frameDelay: auto

# Maximum delay between frames in ms
# Ignored if the 'frameDelay' isn't set to 'auto'
# Set to 'auto' to prevent limiting the max idle time
maxIdleTime: 2000

# Cursor style can be one of
# 'block', 'underline', or 'bar'
cursorStyle: block

# Font family
# You can use any font that is installed on your machine
# in CSS-like syntax
fontFamily: "Monaco, Lucida Console, Ubuntu Mono, Monospace"

# The size of the font
fontSize: 12

# The height of lines
lineHeight: 1

# The spacing between letters
letterSpacing: 0